CREATE TABLE public.users (
  user_id BIGSERIAL PRIMARY KEY,
  balance NUMERIC(38,2) NOT NULL DEFAULT 0,
  email CHARACTER VARYING(255) NOT NULL,
  nickname CHARACTER VARYING(255) NOT NULL,
  password CHARACTER VARYING(255) NOT NULL,
  register_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);